#%RAML 0.8
title: OICSecurityCredentialResource
version: v1.0-20150819
schemas:
 - Cred: !include schemas/oic.r.cred.json

traits:
  - interface:
      queryParameters:
        if:
          enum: ["oic.if.baseline"]
  - cred-filtered:
      usage: Apply this to any method that can filter creds
      description: Some requests only operate on a subset of creds
      queryParameters:
        credid:
            type: integer
            description: Only applies to the credential with the specified credid
            required: false
            repeat: true
            example: 2112
        subjectuuid:
            type: string
            description: Only applies to ACEs with the specified subject UUID
            required: false
            repeat: false
            example: se61c3e6b-9c54-4b81-8ce5-f9039c1d04d9

/oic/sec/cred:
  description: |
    This resource specifies credentials a device may use to establish secure communication.
  displayName: Credential Resource
  is: [ interface ]

  get:

    description: |
      Retrieves the credential data.
      When used without query parameters, all the credential entries are returned.
      When used with a query parameter, only the credentials matching the specified
      parameter are returned.

      Note that write-only credential data will not be returned.
    is: [cred-filtered]
    responses:
      200:
        body:
          application/json:
            schema: Cred
            example: |
              {
                "creds": [
                  {
                    "credid": 55,
                    "subjectuuid": "e61c3e6b-9c54-4b81-8ce5-f9039c1d04d9",
                    "roleid": {
                      "authority": "484b8a51-cb23-46c0-a5f1-b4aebef50ebe",
                      "roles": [
                        "SOME_STRING", "SOME_STRING"
                      ]
                    },
                    "credtype": 32,
                    "publicdata": {
                      "encoding": "oic.sec.encoding.base64",
                      "data": "BASE-64-ENCODED-VALUE"
                    },
                    "privatedata": {
                      "encoding": "oic.sec.encoding.base64",
                      "data": "BASE-64-ENCODED-VALUE",
                      "handle": 4
                    },
                    "optionaldata": {
                      "revstat": false,
                      "encoding": "oic.sec.encoding.base64",
                      "data": "BASE-64-ENCODED-VALUE"
                    },
                    "period": "20160101T180000Z/20170102T070000Z",
                    "crms": [ "oic.sec.crm.pk10" ]
                  },
                  {
                    "credid": 55,
                    "subjectuuid": "e61c3e6b-9c54-4b81-8ce5-f9039c1d04d9",
                    "roleid": {
                      "authority": "484b8a51-cb23-46c0-a5f1-b4aebef50ebe",
                      "roles": [
                        "SOME_STRING", "SOME_STRING"
                      ]
                    },
                    "credtype": 1,
                    "publicdata": {
                      "encoding": "oic.sec.encoding.base64",
                      "data": "BASE-64-ENCODED-VALUE"
                    },
                    "privatedata": {
                      "encoding": "oic.sec.encoding.base64",
                      "data": "BASE-64-ENCODED-VALUE",
                      "handle": 4
                    },
                    "optionaldata": {
                      "revstat": false,
                      "encoding": "oic.sec.encoding.base64",
                      "data": "BASE-64-ENCODED-VALUE"
                    },
                    "period": "20160101T180000Z/20170102T070000Z",
                    "crms": [ "oic.sec.crm.pk10" ]
                  }
                ],
                "rowneruuid": "e61c3e6b-9c54-4b81-8ce5-f9039c1d04d9"
              }
      400:
        description: The request is invalid.

  post:

    description: |
      Updates the credential resource with the provided credentials.

      Credentials provided in the update with credid(s) not currently in the
      credential resource are added.

      Credentials provided in the update with credid(s) already in the
      credential resource completely replace the creds in the credential
      resource.

      Credentials provided in the update without credid(s) properties are
      added and assigned unique credid(s) in the credential resource.
    body:
      application/json:
        schema: Cred
        example: |
          {
            "creds": [
              {
                "credid": 55,
                "subjectuuid": "e61c3e6b-9c54-4b81-8ce5-f9039c1d04d9",
                "roleid": {
                  "authority": "484b8a51-cb23-46c0-a5f1-b4aebef50ebe",
                  "roles": [
                    "SOME_STRING", "SOME_STRING"
                  ]
                },
                "credtype": 32,
                "publicdata": {
                  "encoding": "oic.sec.encoding.base64",
                  "data": "BASE-64-ENCODED-VALUE"
                },
                "privatedata": {
                  "encoding": "oic.sec.encoding.base64",
                  "data": "BASE-64-ENCODED-VALUE",
                  "handle": 4
                },
                "optionaldata": {
                  "revstat": false,
                  "encoding": "oic.sec.encoding.base64",
                  "data": "BASE-64-ENCODED-VALUE"
                },
                "period": "20160101T180000Z/20170102T070000Z",
                "crms": [ "oic.sec.crm.pk10" ]
              },

              {
                "credid": 55,
                "subjectuuid": "e61c3e6b-9c54-4b81-8ce5-f9039c1d04d9",
                "roleid": {
                  "authority": "484b8a51-cb23-46c0-a5f1-b4aebef50ebe",
                  "roles": [
                    "SOME_STRING", "SOME_STRING"
                  ]
                },
                "credtype": 1,
                "publicdata": {
                  "encoding": "oic.sec.encoding.base64",
                  "data": "BASE-64-ENCODED-VALUE"
                },
                "privatedata": {
                  "encoding": "oic.sec.encoding.base64",
                  "data": "BASE-64-ENCODED-VALUE",
                  "handle": 4
                },
                "optionaldata": {
                  "revstat": false,
                  "encoding": "oic.sec.encoding.base64",
                  "data": "BASE-64-ENCODED-VALUE"
                },
                "period": "20160101T180000Z/20170102T070000Z",
                "crms": [ "oic.sec.crm.pk10" ]
              }
            ],
            "rowneruuid": "e61c3e6b-9c54-4b81-8ce5-f9039c1d04d9"
            }
    responses:
      201:
        description: The credential entry is created.
      204:
        description: The credential entry is updated.
      400:
        description: The request is invalid.

  delete:

      description: |
        Deletes credential entries.
        When DELETE is used without query parameters, all the cred entries are deleted.
        When DELETE is used with a query parameter, only the entries matching
        the query parameter are deleted.
      is: [cred-filtered]
      responses:
        204:
          description: The specific credential(s) or the the entire credential resource has been successfully deleted.
        400:
          description: The request is invalid.
