#%RAML 0.8
title: OICSecurityAcl2Resource
version: v1.0-20161214
schemas:
  - Acl2: !include schemas/oic.r.acl2.json

traits:
  - interface:
      queryParameters:
        if:
          enum: ["oic.if.baseline"]
  - ace-filtered:
      usage: Apply this to any method that can filter ACEs
      description: Some requests only operate on a subset of ACEs
      queryParameters:
        aceid:
            type: integer
            description: Only applies to the ACE with the specified aceid
            required: false
            repeat: false
            example: 2112
        subjectuuid:
            type: string
            description: Only applies to ACEs with the specified subject UUID
            required: false
            repeat: false
            example: se61c3e6b-9c54-4b81-8ce5-f9039c1d04d9
        resources:
            type: string
            description: Only applies to ACEs with the specificed subhectuuid |
                         and resources href
            required: false
            repeat: false
            example: coaps://IP-ADDR/temp

/oic/sec/acl2:
  description: |
    This resource specifies the local access control list.

  displayName: Access Control List data
  is: [ interface ]

  get:
    description: |
      Retrieves the ACL data.
      When used without query parameters, all the ACE entries are returned.
      When used with an aceid or resources query parameter, only the
      ACEs matching the specified parameter are returned.
    is: [ace-filtered]
    responses:
      200:
        body:
          application/json:
            schema: Acl2
            example: |
              {
                "aclist": [
                  {
                    "aceid": 1,
                    "subject": {
                      "authority": "484b8a51-cb23-46c0-a5f1-b4aebef50ebe",
                      "roles": [
                        "SOME_STRING", "SOME_STRING"
                      ]
                    },
                    "resources": [
                      {
                        "href": "coaps://IP-ADDR/light",
                        "rel": "some-rel",
                        "rt": ["oic.r.light"],
                        "if": ["oic.if.a"]
                      },
                      {
                        "href": "coaps://IP-ADDR/door",
                        "rel": "some-rel",
                        "rt": ["oic.r.door"],
                        "if": ["oic.if.a"]
                      }
                    ],
                    "permission": 24
                  },
                  {
                    "aceid": 2,
                    "subject": {
                      "uuid": "e61c3e6b-9c54-4b81-8ce5-f9039c1d04d9"
                    },
                    "resources": [
                      {
                        "href": "coaps://IP-ADDR/light",
                        "rel": "some-rel",
                        "rt": ["oic.r.light"],
                        "if": ["oic.if.a"]
                      },
                      {
                        "href": "coaps://IP-ADDR/door",
                        "rel": "some-rel",
                        "rt": ["oic.r.door"],
                        "if": ["oic.if.a"]
                      }
                    ],
                    "permission": 24
                    },
                    {
                      "subject": "*",
                      "resources": [
                        {
                          "href": "coaps://IP-ADDR/light",
                          "rel": "some-rel",
                          "rt": ["oic.r.light"],
                          "if": ["oic.if.a"]
                        },
                        {
                          "href": "coaps://IP-ADDR/door",
                          "rel": "some-rel",
                          "rt": ["oic.r.door"],
                          "if": ["oic.if.a"]
                        }
                      ],
                      "permission": 16,
                      "validity": [
                        {
                          "period":"20160101T180000Z/20170102T070000Z",
                          "recurrence": [ "DSTART:XXXXX", "RRULE:FREQ=DAILY;UNTIL=20180131T140000Z;BYMONTH=1" ]
                        },
                        {
                          "period":"20160101T180000Z/PT5H30M",
                          "recurrence": [ "RRULE:FREQ=DAILY;UNTIL=20180131T140000Z;BYMONTH=1" ]
                        }
                      ]
                    }
                ],
                "rowneruuid": "de305d54-75b4-431b-adb2-eb6b9e546014"
              }
      400:
        description: The request is invalid.

  post:
    description: |
      Updates the ACL resource with the provided values.

      ACEs provided in the update with aceids not currently in the ACL are
      added.

      ACEs provided in the update with aceids already in the ACL replace
      existing ACEs in correspondance with the aceids.

      ACEs provided in the update without aceid entries are added and
      assigned unique aceids.
    body:
      application/json:
        schema: Acl2
        example: |
          {
            "aclist": [
              {
                "aceid": 1,
                "subject": {
                  "authority": "484b8a51-cb23-46c0-a5f1-b4aebef50ebe",
                  "roles": [
                    "SOME_STRING", "SOME_STRING"
                  ]
                },
                "resources": [
                  {
                    "href": "coaps://IP-ADDR/light",
                    "rel": "some-rel",
                    "rt": ["oic.r.light"],
                    "if": ["oic.if.a"]
                  },
                  {
                    "href": "coaps://IP-ADDR/door",
                    "rel": "some-rel",
                    "rt": ["oic.r.door"],
                    "if": ["oic.if.a"]
                  }
                ],
                "permission": 24
              },
              {
                "aceid": 3,
                "subject": {
                  "uuid": "e61c3e6b-9c54-4b81-8ce5-f9039c1d04d9"
                },
                "resources": [
                  {
                    "href": "coaps://IP-ADDR/light",
                    "rel": "some-rel",
                    "rt": ["oic.r.light"],
                    "if": ["oic.if.a"]
                  },
                  {
                    "href": "coaps://IP-ADDR/door",
                    "rel": "some-rel",
                    "rt": ["oic.r.door"],
                    "if": ["oic.if.a"]
                  }
                ],
                "permission": 24
              }
            ],
            "rowneruuid": "e61c3e6b-9c54-4b81-8ce5-f9039c1d04d9"
          }

    responses:
      201:
        description: The ACL entry is created.
      204:
        description: The ACL entry is updated.
      400:
        description: The request is invalid.

  delete:
    description: |
      Deletes ACL entries.
      When DELETE is used without query parameters, all the ACE entries are deleted.
      When DELETE is used with an aceid and/or resources query parameter, only the
      ACEs matching the specified parameter are deleted.
    is: [ace-filtered]
    responses:
      200:
        description: The matching ACEs or the entire ACL resource has been successfully deleted.
      400:
        description: The request is invalid.
