#%RAML 0.8
title: OICSecurityDoxmResource
version: v1.0-20180616
documentation:
  - title: OCF Copyright
    content: Copyright (c) 2016, 2017, 2018 Open Connectivity Foundation, Inc. All rights reserved.
  - title: OCF License
    content: !include LICENSE.md
  - title: OCF Disclaimer
    content: !include DISCLAIMER.md
schemas:
  - Doxm: !include schemas/oic.r.doxm.json
  - Doxm-Update: !include schemas/oic.r.doxm-Update.json

traits:
  - interface:
      queryParameters:
        if:
            enum: ["oic.if.baseline"]

/oic/sec/doxm:
  description: |
    This resource specifies properties needed to establish a device owner.

  displayName: Device owner transfer method resource data
  is: [ interface ]

  get:
    description: |
      Retrieves the DOXM resource data.
    responses:
      200:
        body:
          application/json:
            schema: Doxm
            example: |
              {
                "oxms": [ 0, 2, 3 ],
                "oxmsel": 0,
                "sct": 16,
                "owned": true,
                "deviceuuid": "de305d54-75b4-431b-adb2-eb6b9e546014",
                "devowneruuid": "e61c3e6b-9c54-4b81-8ce5-f9039c1d04d9",
                "rowneruuid": "e61c3e6b-9c54-4b81-8ce5-f9039c1d04d9"
              }

      400:
        description: The request is invalid.

  post:
    description: |
      Updates the DOXM resource data
    body:
      application/json:
        schema: Doxm-Update
        example: |
          {
            "oxmsel": 0,
            "owned": true,
            "deviceuuid": "de305d54-75b4-431b-adb2-eb6b9e546014",
            "devowneruuid": "e61c3e6b-9c54-4b81-8ce5-f9039c1d04d9",
            "rowneruuid": "e61c3e6b-9c54-4b81-8ce5-f9039c1d04d9"
          }
    responses:
      201:
        description: The DOXM entry is created.
      204:
        description: The DOXM entry is updated.
      400:
        description: The request is invalid.

  put:
    description: |
      Creates the DOXM resource data
    body:
      application/json:
        schema: Doxm-Update
        example: |
          {
            "oxmsel": 0,
            "owned": true,
            "deviceuuid": "de305d54-75b4-431b-adb2-eb6b9e546014",
            "devowneruuid": "e61c3e6b-9c54-4b81-8ce5-f9039c1d04d9",
            "rowneruuid": "e61c3e6b-9c54-4b81-8ce5-f9039c1d04d9"
          }
    responses:
      201:
        description: The DOXM entry is created.
      400:
        description: The request is invalid.
