#%RAML 0.8
title: OICSecurityAclResource
version: v1.1-20161213
schemas:
  - Acl: !include schemas/oic.r.acl.json

traits:
  - interface:
      queryParameters:
        if:
          enum: ["oic.if.baseline"]

/oic/sec/acl:
  description: |
    This resource specifies the local access control list.

  displayName: Access Control List data
  is: [ interface ]

  get:
    description: |
      Retrieves the ACL data.
      When used without query parameters, all the ACE entries are returned.
      When used with a subjectuuid or resources query parameter, only the
      ACEs matching the specified parameter are returned.
    queryParameters:
        subjectuuid:
            type: string
            description: |
              Returns ACEs with the specificed subject UUID
            required: false
            repeat: false
            example: se61c3e6b-9c54-4b81-8ce5-f9039c1d04d9
        resources:
            type: string
            description: |
              Returns ACEs with the specificed resource href
            required: false
            repeat: false
            example: coaps://IP-ADDR/temp
    responses:
      200:
        body:
          application/json:
            schema: Acl
            example: |
              {
                "aclist": {
                  "aces": [
                    {
                      "subjectuuid": "e61c3e6b-9c54-4b81-8ce5-f9039c1d04d9",
                      "resources": [
                        {
                          "href": "coaps://IP-ADDR/temp",
                          "rel": "some-rel",
                          "rt": ["oic.r.temperature"],
                          "if": ["oic.if.a"]
                        },
                        {
                          "href": "coaps://IP-ADDR/temp",
                          "rel": "some-rel",
                          "rt": ["oic.r.temperature"],
                          "if": ["oic.if.s"]
                        }
                      ],
                      "permission": 31,
                      "validity": [
                        {
                          "period":"20160101T180000Z/20170102T070000Z",
                          "recurrence": [ "DSTART:XXXXX", "RRULE:FREQ=DAILY;UNTIL=20180131T140000Z;BYMONTH=1" ]
                        },
                        {
                          "period":"20160101T180000Z/PT5H30M",
                          "recurrence": [ "RRULE:FREQ=DAILY;UNTIL=20180131T140000Z;BYMONTH=1" ]
                        }
                      ]
                    }
                  ]
                },
                "rowneruuid": "de305d54-75b4-431b-adb2-eb6b9e546014"
              }
      400:
        description: The request is invalid.

  post:
    description: |
      Updates the ACL resource with the provided values. ACEs provided
      in the update not currently in the ACL are added. ACEs that already
      exist in the ACL are ignored.
    body:
      application/json:
        schema: Acl
        example: |
          {
            "aclist": {
              "aces": [
                {
                  "subjectuuid": "e61c3e6b-9c54-4b81-8ce5-f9039c1d04d9",
                  "resources": [
                    {
                      "href": "coaps://IP-ADDR/temp",
                      "rel": "some-rel",
                      "rt": ["oic.r.temperature"],
                      "if": ["oic.if.a"]
                    },
                    {
                      "href": "coaps://IP-ADDR/temp",
                      "rel": "some-rel",
                      "rt": ["oic.r.temperature"],
                      "if": ["oic.if.s"]
                    }
                  ],
                  "permission": 31,
                  "validity": [
                    {
                      "period":"20160101T180000Z/20170102T070000Z",
                      "recurrence": [ "DSTART:XXXXX", "RRULE:FREQ=DAILY;UNTIL=20180131T140000Z;BYMONTH=1" ]
                    },
                    {
                      "period":"20160101T180000Z/PT5H30M",
                      "recurrence": [ "RRULE:FREQ=DAILY;UNTIL=20180131T140000Z;BYMONTH=1" ]
                    }
                  ]
                }
              ]
            },
            "rowneruuid": "de305d54-75b4-431b-adb2-eb6b9e546014"
          }

    responses:
      201:
        description: The ACL entry/entries is/are created.
      204:
        description: The ACL entry/entries is/are updated.
      400:
        description: The request is invalid.

  delete:
    description: |
      Deletes ACL entries.
      When DELETE is used without query parameters, all the ACE entries are deleted.
      When DELETE is used with a subjectuuid or resources query parameter, only the
      ACEs matching the specified parameter are deleted.
    queryParameters:
        subjectuuid:
            type: string
            description: |
              Deletes the ACL(s) identified by the string containing subjectuuid.
              e.g. DELETE /myacl?subjectuuid="de305d54-75b4-431b-adb2-eb6b9e546014"
            required: false
            example: de305d54-75b4-431b-adb2-eb6b9e546014
        resources:
            type: string
            description: |
              Deletes ACEs with the specificed resource href
            required: false
            repeat: false
            example: coaps://IP-ADDR/temp

    responses:
      200:
        description: The matching ACL instances or the the entire ACL resource has been successfully deleted.
      400:
        description: The request is invalid.
