#%RAML 0.8
title: OICSecurityRolesResource
version: v1.0-20170323
documentation:
  - title: OCF Copyright
    content: Copyright (c) 2016, 2017 Open Connectivity Foundation, Inc. All rights reserved.
  - title: OCF License
    content: !include LICENSE.md
  - title: OCF Disclaimer
    content: !include DISCLAIMER.md
schemas:
  - Roles: !include schemas/oic.r.roles.json
  - Roles-update: !include schemas/oic.r.roles-Update.json
traits:
  - interface:
      queryParameters:
        if:
          enum: ["oic.if.baseline"]
  - roles-filtered:
      usage: Apply this to any method that can filter roles
      description: Some requests only operate on a subset of roles
      queryParameters:
        credid:
            type: integer
            description: Only applies to the credential with the specified credid
            required: false
            repeat: true
            example: 2112

/oic/sec/roles:
  description: |
    This resource specifies roles that have been asserted.

  displayName: Asserted Roles Data
  is: [ interface ]

  get:
    description: |
      Retrieves the asserted roles data.
    responses:
      200:
        body:
          application/json:
            schema: Roles
            example: |
              {
                "roles" :[
                    {
                      "credid":1,
                      "credtype":8,  # Cred type 8 is SIGNED_ASYMMETRIC_KEY
                      "subjectuuid":"00000000-0000-0000-0000-000000000000",
                      "publicdata":
                        {
                           "encoding":"oic.sec.encoding.pem",
                           "data":"PEMENCODEDROLECERT"
                        },
                      "optionaldata":        # Optional issuer certificate, type oic.sec.pubdatatype
                        {
                           "encoding":"oic.sec.encoding.pem",
                           "data":"PEMENCODEDISSUERCERT"
                        }
                    },
                    {
                      "credid":2,
                      "credtype":8,  # Cred type 8 is SIGNED_ASYMMETRIC_KEY
                      "subjectuuid":"00000000-0000-0000-0000-000000000000",
                      "publicdata":
                        {
                           "encoding":"oic.sec.encoding.pem",
                           "data":"PEMENCODEDROLECERT"
                        },
                      "optionaldata":
                        {
                           "encoding":"oic.sec.encoding.pem",
                           "data":"PEMENCODEDISSUERCERT"
                        }
                    }
                ],
                "rt":["oic.r.roles"],
                "if":["oic.if.baseline"]
              }
      400:
        description: The request is invalid.

  post:
    description: |
      Update the roles resource, i.e., assert new roles to this server.

      New role certificates that match an existing certificate (i.e., publicdata
      and optionaldata are the same) are not added to the resource (and 204 is
      returned).

      The provided credid values are ignored, the resource assigns its own.

    body:
      application/json:
        schema: Roles-update
        example: |
          {
            "roles" :[
                {
                  "credid":1,    # Optional
                  "credtype":8,  # Cred type 8 is SIGNED_ASYMMETRIC_KEY
                  "subjectuuid":"00000000-0000-0000-0000-000000000000",
                  "publicdata":
                    {
                       "encoding":"oic.sec.encoding.pem",
                       "data":"PEMENCODEDROLECERT"
                    },
                  "optionaldata":
                    {
                       "encoding":"oic.sec.encoding.pem",
                       "data":"PEMENCODEDISSUERCERT"
                    }
                },
                {
                  "credid":2,    #Optional
                  "credtype":8,  # Cred type 8 is SIGNED_ASYMMETRIC_KEY
                  "subjectuuid":"00000000-0000-0000-0000-000000000000",
                  "publicdata":
                    {
                       "encoding":"oic.sec.encoding.pem",
                       "data":"PEMENCODEDROLECERT"
                    },
                  "optionaldata":
                    {
                       "encoding":"oic.sec.encoding.pem",
                       "data":"PEMENCODEDISSUERCERT"
                    }
                }
            ],
            "rt":["oic.r.roles"],
            "if":["oic.if.baseline"]
            }

    responses:
      204:
        description: The roles entry is updated.
      400:
        description: The request is invalid.

  delete:
    description: |
      Deletes roles resource entries.
      When DELETE is used without query parameters, all the roles entries are deleted.
      When DELETE is used with a query parameter, only the entries matching
      the query parameter are deleted.
      is: [roles-filtered]
    responses:
      200:
        description: The specified or all roles resource entries have been successfully deleted.
      400:
        description: The request is invalid.
