#%RAML 0.8
title: Security Profile Resource
version: v1.0-20180831
documentation:
  - title: OCF Copyright
    content: Copyright (c) 2018 Open Connectivity Foundation, Inc. All rights reserved.
  - title: OCF License
    content: !include LICENSE.md
  - title: OCF Disclaimer
    content: !include DISCLAIMER.md
schemas:
  - SP: !include schemas/oic.r.sp.json
  - SP-Update: !include schemas/oic.r.sp-Update.json

traits:
  - interface:
      queryParameters:
        if:
            enum: ["oic.if.baseline"]

/oic/sec/sp:
  description: |
    Resource specifying supported and active Security Profile(s)

  displayName: Security Profile Resource
  is: [ interface ]

  get:
    description: |
      Retrieves Security Profile data
    responses:
      200:
        body:
          application/json:
            schema: SP
            example: |
              {
                "rt": ["oic.r.sp"],
                "supportedprofiles" : ["1.3.6.1.4.1.51414.0.1.0", " 1.3.6.1.4.1.51414.0.2.0"],
                "currentprofile" : "1.3.6.1.4.1.51414.0.1.0"
              }
      400:
        description: The request is invalid.

  post:
    description: |
      Sets or updates device provisioning status data.
    body:
      application/json:
        schema: SP-Update
        example: |
          {
            "supportedprofiles" : ["1.3.6.1.4.1.51414.0.1.0", " 1.3.6.1.4.1.51414.0.2.0"],
            "currentprofile" : "1.3.6.1.4.1.51414.0.1.0"
          }
    responses:
      200:
        body:
          application/json:
            schema: SP
            example: |
              {
                "rt": ["oic.r.sp"],
                "supportedprofiles" : ["1.3.6.1.4.1.51414.0.1.0", " 1.3.6.1.4.1.51414.0.2.0"],
                "currentprofile" : "1.3.6.1.4.1.51414.0.1.0"
              }
      400:
        description: The request is invalid.
