#%RAML 0.8
title: OICSecurityAclResource
version: v1.0-20150819
schemas:
  - Acl: !include schemas/oic.r.acl.json

traits:
  - interface:
      queryParameters:
        if:
          enum: ["oic.if.baseline"]

/SecAclResURI:
  description: |
    This resource specifies the local access control list.

  displayName: Access Control List data
  is: [ interface ]

  get:
    description: |
      Retrieves the acl data.
    responses:
      200:
        body:
          application/json:
            schema: Acl
            example: |
              {
                "aclist": [
                  {
                    "subject": {
                      "rl": {
                        "authority": "484b8a51-cb23-46c0-a5f1-b4aebef50ebe",
                        "roles": [
                          "SOME_STRING", "SOME_STRING"
                        ]
                      }
                    },
                    "resources": [
                      {
                        "href": "coaps://IP-ADDR/light",
                        "rel": "some-rel",
                        "rt": ["oic.r.light"],
                        "if": ["oic.if.a"]
                      },
                      {
                        "href": "coaps://IP-ADDR/door",
                        "rel": "some-rel",
                        "rt": ["oic.r.door"],
                        "if": ["oic.if.a"]
                      }
                    ],
                    "permission": 24
                  },
                  {
                    "subject": {
                      "idt": "0",
                      "id": "e61c3e6b-9c54-4b81-8ce5-f9039c1d04d9"
                    },
                    "resources": [
                      {
                        "href": "coaps://IP-ADDR/light",
                        "rel": "some-rel",
                        "rt": ["oic.r.light"],
                        "if": ["oic.if.a"]
                      },
                      {
                        "href": "coaps://IP-ADDR/door",
                        "rel": "some-rel",
                        "rt": ["oic.r.door"],
                        "if": ["oic.if.a"]
                      }
                    ],
                    "permission": 24
                  }
                ],
                "rowneruuid": "de305d54-75b4-431b-adb2-eb6b9e546014",
                "rowner": {
                  "hostid": {
                    "idt": "0",
                    "id": "e61c3e6b-9c54-4b81-8ce5-f9039c1d04d9"
                  }
                }
              }
      400:
        description: The request is invalid.

  post:
    description: |
      Updates the ACL resource with the provided values.
    body:
      application/json:
        schema: Acl
        example: |
          {
            "aclist": [
              {
                "subject": {
                  "rl": {
                    "authority": "484b8a51-cb23-46c0-a5f1-b4aebef50ebe",
                    "roles": [
                      "SOME_STRING", "SOME_STRING"
                    ]
                  }
                },
                "resources": [
                  {
                    "href": "coaps://IP-ADDR/light",
                    "rel": "some-rel",
                    "rt": ["oic.r.light"],
                    "if": ["oic.if.a"]
                  },
                  {
                    "href": "coaps://IP-ADDR/door",
                    "rel": "some-rel",
                    "rt": ["oic.r.door"],
                    "if": ["oic.if.a"]
                  }
                ],
                "permission": 24
              },
              {
                "subject": {
                  "idt": "0",
                  "id": "e61c3e6b-9c54-4b81-8ce5-f9039c1d04d9"
                },
                "resources": [
                  {
                    "href": "coaps://IP-ADDR/light",
                    "rel": "some-rel",
                    "rt": ["oic.r.light"],
                    "if": ["oic.if.a"]
                  },
                  {
                    "href": "coaps://IP-ADDR/door",
                    "rel": "some-rel",
                    "rt": ["oic.r.door"],
                    "if": ["oic.if.a"]
                  }
                ],
                "permission": 24
              }
            ],
            "rowneruuid": "de305d54-75b4-431b-adb2-eb6b9e546014",
            "rowner": {
              "hostid": {
                "idt": "0",
                "id": "e61c3e6b-9c54-4b81-8ce5-f9039c1d04d9"
              }
            }
          }

    responses:
      201:
        description: The ACL entry is created.
      204:
        description: The ACL entry is updated.
      400:
        description: The request is invalid.

  put:
    description: |
      Creates the new acl data
    body:
      application/json:
        schema: Acl
        example: |
          {
            "aclist": [
              {
                "subject": {
                  "rl": {
                    "authority": "484b8a51-cb23-46c0-a5f1-b4aebef50ebe",
                    "roles": [
                      "SOME_STRING", "SOME_STRING"
                    ]
                  }
                },
                "resources": [
                  {
                    "href": "coaps://IP-ADDR/light",
                    "rel": "some-rel",
                    "rt": ["oic.r.light"],
                    "if": ["oic.if.a"]
                  },
                  {
                    "href": "coaps://IP-ADDR/door",
                    "rel": "some-rel",
                    "rt": ["oic.r.door"],
                    "if": ["oic.if.a"]
                  }
                ],
                "permission": 24
              },
              {
                "subject": {
                  "idt": "0",
                  "id": "e61c3e6b-9c54-4b81-8ce5-f9039c1d04d9"
                },
                "resources": [
                  {
                    "href": "coaps://IP-ADDR/light",
                    "rel": "some-rel",
                    "rt": ["oic.r.light"],
                    "if": ["oic.if.a"]
                  },
                  {
                    "href": "coaps://IP-ADDR/door",
                    "rel": "some-rel",
                    "rt": ["oic.r.door"],
                    "if": ["oic.if.a"]
                  }
                ],
                "permission": 24
              }
            ],
            "rowneruuid": "de305d54-75b4-431b-adb2-eb6b9e546014",
            "rowner": {
              "hostid": {
                "idt": "0",
                "id": "e61c3e6b-9c54-4b81-8ce5-f9039c1d04d9"
              }
            }
          }

    responses:
      201:
        description: The ACL entry is created.
      400:
        description: The request is invalid.

  delete:
    description: |
      Deletes ACL entries.
      When DELETE is used without query parameters, all the acl entries are deleted.
      When DELETE is used with a subjectuuid query parameter, only the entries matching the subjectuuid are deleted.
    queryParameters:
        subjectuuid:
            type: string
            description: |
              Deletes the ACL(s) identified by the string containing subjectuuid.
              e.g. DELETE /myacl?subjectuuid="de305d54-75b4-431b-adb2-eb6b9e546014"
            required: false
            example: |
                DELETE /myacl?subjectuuid="de305d54-75b4-431b-adb2-eb6b9e546014"

    responses:
      200:
        description: The matching ACL instances or the the entire ACL resource has been successfully deleted.
      400:
        description: The request is invalid.
